const TYPES = {
  GET_DUMMY_DATA: "GET_DUMMY_DATA",
  GET_DUMMY_DATA_SUCCESS: "GET_DUMMY_DATA_SUCCESS",
  GET_DUMMY_DATA_FAILED: "GET_DUMMY_DATA_FAILED",
  GET_HEADER_AUDIO_DATA: "GET_HEADER_AUDIO_DATA",
  SET_HEADER_AUDIO_DATA: "SET_HEADER_AUDIO_DATA",
  GET_HEADER_AUDIO_DATA_SUCCESS: "GET_HEADER_AUDIO_DATA_SUCCESS",
  GET_HEADER_AUDIO_DATA_FAILED: "GET_HEADER_AUDIO_DATA_FAILED",
  GET_HEADER_AUDIO_ENABLE_TRUE: "GET_HEADER_AUDIO_ENABLE_TRUE",
  GET_HEADER_AUDIO_ENABLE_FALSE: "GET_HEADER_AUDIO_ENABLE_FALSE",
  GET_HOME_PAGE_DATA: "GET_HOME_PAGE_DATA",
  GET_HOME_PAGE_DATA_SUCCESS: "GET_HOME_PAGE_DATA_SUCCESS",
  GET_HOME_PAGE_DATA_FAILED: "GET_HOME_PAGE_DATA_FAILED",
  GET_HOME_PAGE_ATTACHMENT_DATA: "GET_HOME_PAGE_ATTACHMENT_DATA",
  GET_HOME_PAGE_ATTACHMENT_DATA_SUCCESS:
    "GET_HOME_PAGE_ATTACHMENT_DATA_SUCCESS",
  GET_HOME_PAGE_ATTACHMENT_DATA_FAILED: "GET_HOME_PAGE_ATTACHMENT_DATA_FAILED",
  GET_HOME_PAGE_DATA_ATTACHMENT_UPDATE: "GET_HOME_PAGE_DATA_ATTACHMENT_UPDATE",
  SAVE_QUIZ_FIELDS: "SAVE_QUIZ_FIELDS",

  GET_HOME_PAGE_DATA_INITIAL_STATE: "GET_HOME_PAGE_DATA_INITIAL_STATE",
  PAGE_SPINNER_TOGGLE: "PAGE_SPINNER_TOGGLE",
  GET_QUIZ_QUESTIONS: "GET_QUIZ_QUESTIONS",
  GET_QUIZ_QUESTIONS_SUCCESS: "GET_QUIZ_QUESTIONS_SUCCESS",
  GET_QUIZ_QUESTIONS_FAILURE: "GET_QUIZ_QUESTIONS_FAILURE",
  GET_COMMON_QUESTION_REQUEST: "GET_COMMON_QUESTION_REQUEST",
  GET_COMMON_QUESTION_REQUEST_SUCCESS: "GET_COMMON_QUESTION_REQUEST_SUCCESS",
  GET_COMMON_QUESTION_REQUEST_FAILURE: "GET_COMMON_QUESTION_REQUEST_FAILURE",

  POST_QUIZ_REQUEST: "POST_QUIZ_REQUEST",
  POST_QUIZ_REQUEST_SUCCESS: "POST_QUIZ_REQUEST_SUCCESS",
  POST_QUIZ_REQUEST_FAILURE: "POST_QUIZ_REQUEST_FAILURE",

  USER_INFO_REQUEST: "USER_INFO_REQUEST",
  USER_INFO_REQUEST_SUCCESS: "USER_INFO_REQUEST_SUCCESS",
  USER_INFO_REQUEST_FAILURE: "USER_INFO_REQUEST_FAILURE",
  LOGOUT_USER: "LOGOUT_USER",

  REGISTER_USER: "REGISTER_USER",
  REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
  REGISTER_USER_FAILURE: "REGISTER_USER_FAILURE",

  LOGIN_USER: "LOGIN_REQUEST",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_FAILURE: "LOGIN_USER_FAILURE",
  PROMO_CODE: "PROMO_CODE",

  RESET_PAYLOAD: "RESET_PAYLOAD",

  BETA: "BETA",

  ADD_VALIDATED_EMAIL: "ADD_VALIDATED_EMAIL"
}

export default TYPES
