const AppDataConstant = {
  homeQuizBg:
    "https://practical0001.blob.core.windows.net/public/bg/quiz-bg.png",
  homeQuizBgWebp:
    "https://practical0001.blob.core.windows.net/public/banner/quiz-bg-webp.webp",
  thankYouQuizBg:
    "https://practical0001.blob.core.windows.net/public/bg/thanyoubg.png",
  bannerSliderBlobVideo:
    "https://practical0001.blob.core.windows.net/public/video/video-check-sm.mp4",
  bannerSliderBlobVideoMobile:
    "https://practical0001.blob.core.windows.net/public/video/video-check-sm-mobile.mp4",
  bannerSliderVideo:
    "https://assets.practical.me/public/video/video-check-sm.mp4",
  bannerSliderVideoMobile:
    "https://assets.practical.me/public/video/video-check-sm-mobile.mp4",
  bannerBG:
    "https://assets.practical.me/public/banner/banner-bg-lg.png",
  bannerBGNew:
    "https://practical0001.blob.core.windows.net/public/banner/Bannerwebp.webp",
  bannerBGNew:
    "https://assets.practical.me/public/banner/Bannerwebp.webp",
  contactUs:
    "https://assets.practical.me/public/blogs/whatsappContactUs.png",
  mailUs:
    "https://assets.practical.me/public/blogs/mail.png",
  logoutWhite:
    "https://assets.practical.me/public/icons/logout-white2lg.png",
  logoutGreen:
    "https://assets.practical.me/public/icons/logout2lg.png",
  logoutOrange:
    "/images/icons/logoutOrange.png",
  whatsappLogo:
    "https://assets.practical.me/public/logo/whatsapp2x.png",
  inboxBg:
    "https://assets.practical.me/public/blogs/inboxBg.png",
  inboxBgLG:
    "https://assets.practical.me/public/blogs/inboxBgDesktop.png",
  inboxBgLGOrange:
    "/images/bg/quiz-bg-isExecutive.png",
  backarrowWhite:
    "https://assets.practical.me/public/thumb/backArrow2.png",
  backarrowWhiteLG:
    "https://assets.practical.me/public/thumb/backArrow-lg2.png",
  backarrowGreen:
    "https://assets.practical.me/public/thumb/backArrow2-green.png",
  backarrowGreenLG:
    "https://assets.practical.me/public/thumb/backArrow-green-lg.png",
  backarrowOrange:
    require("../../public/images/bg/test.png"),
  backarrowOrangeLG:
    require("../../public/images/bg/test.png"),
  visaIcon:
    "https://assets.practical.me/public/icons/visa-lg.png",
  cardRemoveIcon:
    "https://assets.practical.me/public/icons/cardRemove.png",
  visaSm:
    "https://assets.practical.me/public/logo/visa.png",
  blogLogo1:
    "https://assets.practical.me/public/blogs/logo1.png",
  blogLogo1LG:
    "https://assets.practical.me/public/blogs/logo1Desktop.png",
  blogLogo2:
    "https://assets.practical.me/public/blogs/logo2.png",
  blogLogo2LG:
    "https://assets.practical.me/public/blogs/logo2Desktop.png",
  blogLogo3:
    "https://assets.practical.me/public/blogs/logo3.png",
  blogLogo3LG:
    "https://assets.practical.me/public/blogs/logo3Desktop.png",
  blogLogo4:
    "https://assets.practical.me/public/partners/nourish-new-logo-lg.png",
  blogLogo4LG:
    "https://assets.practical.me/public/partners/nourish-new-logo.png",
  rate: "https://assets.practical.me/public/meal/rate.png",
  rateGreen:
    "https://assets.practical.me/public/meal/rate-green.png",
  chrisBG:
    "https://assets.practical.me/public/bg/chris-bg-sm.png",
  chrisBGLG:
    "https://assets.practical.me/public/bg/chris-bg.png",
  macroVideo:
    "https://assets.practical.me/public/video/macroVideo.mp4",
  macroPoster:
    "https://assets.practical.me/public/video/poster-practical.png",
  passIcon:
    "https://assets.practical.me/public/thumb/pass.png",
  counterDec:
    "https://assets.practical.me/public/thumb/counterDec.png",
  counterInc:
    "https://assets.practical.me/public/thumb/counterInc.png",
  howItWorks:
    "https://assets.practical.me/public/video/how-it-works.mp4",
  masterCard:
    "https://assets.practical.me/public/icons/masterCard.png",
  bannerImg:
    "https://practical0001.blob.core.windows.net/public/banner/bannrWebp.webp",
  bannerImgMob:
    "https://practical0001.blob.core.windows.net/public/banner/bannrWebp.webp",
  googleReview:
    "https://practical0001.blob.core.windows.net/public/icons/google-review.png",
  googleReviewWebp:
    "https://practical0001.blob.core.windows.net/public/banner/google-review.webp",
  inactivityModal:
    "https://practical0001.blob.core.windows.net/public/banner/modaldesk.webp",
  inactivityModalSm: "/images/Dashboard/modaldeskSm.webp",

}

export default AppDataConstant
