const AppRoutes = {
  hash: "#",
  home: "/",
  dashboard: "/dashboard",
  login: "/login",
  signup: "/signup",
  quizB: "/quicksignup",
  thankyou: "/thankyou",
  result: "/result",
  swapItem: "/swapItem",
  quizPreferences: "/quizPreferences",
  forgotPassword: "forgotPassword",
  changePassword: "/changePassword",
  checkOut: "/checkout",
  renewal: "/renewal",
  whatsapp: "https://wa.me/+971523271183",
  // whatsapp: "https://wa.me/971585987044",
  confirmCheckOut: "/confirmCheckout",
  orderComplete: "/orderComplete",
  resetLink: "/resetLink",
  resultNew: "/resultNew",
  mailUs: "mailto:hello@practical.me",
  instaGram: "https://www.instagram.com/wearepractical/",
  passChangeSuccess: "/passwordUpdated",
  diningOut: "/diningout",
  macros: "/macros",
  faqs: "/faqs",
  partnerOffers: "/partner-offers",
  praticalLanding: "https://prelaunch.practical.me/",
  contactUs: "/contact",
  viewRenewal: "/view-renewal",
  termCondition: "/terms-conditions",
  privacy: "/privacy",
  howItWorks: "/howitworks",
  ourMenu: "/ourmenu",
  liveWebsiteURL: 'https://practical.me/',
  mealPricing:'/meal-pricing',
  nofound:'/404',
}

export default AppRoutes
