export const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

const dataRepsonse = {
    id: 7312,
    title: "Aliquam suscipit id",
    promo_code: "TES$$$",
    promo_type: "general_email",
    associated_emails: ["musaib.jeelani@gmail.com"],
    ambassador_email: null,
    ambassador_user_id: null,
    ambassador_referral_codes: [],
    wallet_credit_ratio: "1:26",
    promo_restrictions: "renewal_customers",
    team_member: 1701,
    created_on: "2025-08-06 09:39:00",
    validity_type: "duration_from_creation",
    duration_from_creation: 35,
    duration_from_use: null,
    max_use_per_customer: 95,
    max_use_total: 21,
    discount_on: ["meals", "snacks"],
    status: 0,
    type: "general_email",
    value: 20,
    key: "admin_created",
    start_date: null,
    expiry_date: null,
    users: null,
    length_plan_weeks: [1, 4],
    is_multi_use: 0,
    meal: [2, 4],
    snack: [2, 3, 4],
    days: [],
    company_id: null,
    parent_id: null,
    parent: null,
    company: [],
    discount_plan_lengths: [
        {
            id: 3490,
            discount_id: 7312,
            plan_length: "4",
            reward_type: "flat",
            reward_value: "89.00",
            cap_amount: null,
            wallet_credit_enabled: 1,
            wallet_credit_expiry_date: "1994-04-03T17:23:00.000000Z",
            status: 0,
            created_at: "2025-08-06T05:41:06.000000Z",
            updated_at: "2025-08-06T05:41:06.000000Z",
        },
        {
            id: 3489,
            discount_id: 7312,
            plan_length: "1",
            reward_type: "percentage",
            reward_value: "48.00",
            cap_amount: null,
            wallet_credit_enabled: 0,
            wallet_credit_expiry_date: null,
            status: 0,
            created_at: "2025-08-06T05:41:06.000000Z",
            updated_at: "2025-08-06T05:41:06.000000Z",
        },
    ],
};
const dataRepsonse2 = {
    id: 7312,
    title: "Aliquam suscipit id",
    promo_code: "TES$$$",
    promo_type: "general_email",
    associated_emails: ["musaib.jeelani@gmail.com"],
    ambassador_email: null,
    ambassador_user_id: null,
    ambassador_referral_codes: [],
    wallet_credit_ratio: "1:26",
    promo_restrictions: "renewal_customers",
    team_member: 1701,
    created_on: "2025-08-06 09:39:00",
    validity_type: "duration_from_creation",
    duration_from_creation: 35,
    duration_from_use: null,
    max_use_per_customer: 95,
    max_use_total: 21,
    discount_on: ["meals", "snacks"],
    status: 0,
    type: "general_email",
    value: 20,
    key: "admin_created",
    start_date: null,
    expiry_date: null,
    users: null,
    length_plan_weeks: "All",
    is_multi_use: 0,
    meal: "All",
    snack: "All",
    days: "All",
    company_id: null,
    parent_id: null,
    parent: null,
    company: [],
    discount_plan_lengths: [
        {
            id: 3490,
            discount_id: 7312,
            plan_length: "4",
            reward_type: "flat",
            reward_value: "89.00",
            cap_amount: null,
            wallet_credit_enabled: 1,
            wallet_credit_expiry_date: "1994-04-03T17:23:00.000000Z",
            status: 0,
            created_at: "2025-08-06T05:41:06.000000Z",
            updated_at: "2025-08-06T05:41:06.000000Z",
        },
        {
            id: 3489,
            discount_id: 7312,
            plan_length: "1",
            reward_type: "percentage",
            reward_value: "48.00",
            cap_amount: null,
            wallet_credit_enabled: 0,
            wallet_credit_expiry_date: null,
            status: 0,
            created_at: "2025-08-06T05:41:06.000000Z",
            updated_at: "2025-08-06T05:41:06.000000Z",
        },
    ],
};
const dataRepsonse3 = {
    "id": 5,
    "title": "tatheer4901",
    "promo_code": "TATHEER4901",
    "promo_type": "referal_friend",
    "associated_emails": [],
    "ambassador_email": null,
    "ambassador_user_id": null,
    "ambassador_referral_codes": [],
    "wallet_credit_ratio": "1:5",
    "promo_restrictions": "all_customers",
    "team_member": 1,
    "created_on": "2025-08-07 12:44:00",
    "validity_type": "duration",
    "duration_from_creation": null,
    "duration_from_use": null,
    "max_use_per_customer": null,
    "max_use_total": null,
    "discount_on": [],
    "status": 0,
    "type": "referal_friend",
    "value": 20,
    "key": "referal_friend",
    "start_date": null,
    "expiry_date": null,
    "users": "[196]",
    "length_plan_weeks": [],
    "is_multi_use": 0,
    "meal": [
        1,
        2,
        3,
        4,
        5
    ],
    "snack": [
        1,
        2,
        3,
        4,
        5
    ],
    "days": [],
    "company_id": null,
    "parent_id": null,
    "parent": null,
    "company": [],
    "discount_plan_lengths": [],
    "discount_tiers": [
        {
            "id": 1,
            "week": 1,
            "reward_value": "10.00",
            "referrer_amount": "10.00",
            "key": "standard",
            "created_at": "2025-08-05T14:09:57.000000Z",
            "updated_at": "2025-08-05T14:09:57.000000Z"
        },
        {
            "id": 2,
            "week": 2,
            "reward_value": "15.00",
            "referrer_amount": "25.00",
            "key": "standard",
            "created_at": "2025-08-05T14:09:57.000000Z",
            "updated_at": "2025-08-05T14:09:57.000000Z"
        },
        {
            "id": 3,
            "week": 4,
            "reward_value": "20.00",
            "referrer_amount": "50.00",
            "key": "standard",
            "created_at": "2025-08-05T14:09:57.000000Z",
            "updated_at": "2025-08-05T14:09:57.000000Z"
        }
    ]
}

export default async function handler(req, res) {
    await delay(500); // Delay for 500ms
    res.status(200).json(dataRepsonse);
}
